Makefile
debbuild
debbuild.spec

After four months `debbuild` has transformed beautifully and deserves a new version number.

Papillon 0.15.11

---

debbuild
debbuild.spec
glomacros

This pull request includes various fixes for debbuild to correct behavior with `%{ubuntu}`, `%global`, and environment setup.
Additionally, `%make_build` from RPM 4.12 (included in Debian 8.x / Ubuntu 15.04+) is now supported.

Various fixes for debbuild

---

glomacros

The `%_topdir` macro still pointed to ~/rpmbuild, which needed to be changed.

Fix default %_topdir to point to ~/debbuild

---

debbuild

values in /etc/os-release or /etc/lsb-release may be quoted

allow values to be quoted in release files

---

debbuild

This pull request addresses #44 and #45 by utilizing `lsb_release` in the event that `/etc/os-release` is unavailable.
The logic is simplified as it now has a hard dependency on *either* the presence of `/etc/os-release` or `lsb_release` programs. This will satisfy nearly all Linux distributions in use today.
For this code to work, distributions that don't provide `/etc/os-release` need `/usr/bin/lsb_release` installed instead.
WARNING: I have not tested this code. I'm not great with Perl, so a review to ensure it actually works as intended would be appreciated.
One case I'm not sure how to handle is getting Debian's codename out of `/etc/os-release`. They don't specify a `DEBIAN_CODENAME` value, but instead stick it in `VERSION`.
For example, Debian 8 defines `VERSION` as `"8 (jessie)"`. …

WIP: Fix OS detection to use either os-release(5) or 'lsb_release' only

---

debbuild
debbuild.spec

This PR contains a couple of small fixes:
* The addition of `lsb-release` as a runtime dependency. This is necessary for old Debian/Ubuntu systems to work correctly with `debbuild`.
* The removal of the note about different behaviors of `BuildArch` between RPM and debbuild. RPM has had the same behavior since RPM 4.6.0.

A couple of small fixes

---

debbuild

Modern RPM based systems (Fedora, RHEL/CentOS 7, Mageia, openSUSE 42.2+, etc.) use `%license` for storing license files (like `LICENSE`, `COPYING`, `debian/copyright`, etc.). in a special location (`/usr/share/licenses/<packagename>`).
In the case for Debian, this doesn't really exist. So, `%license` exists purely as an alias for `%doc` and installs it to the same location documentation goes.
Eh, this is where it all used to go before the creation of `%license`, anyway...

Add handling for %license

---

debbuild

The Debian-specific `Breaks` statement is a complement for `Replaces` when it comes to upgrades. It's a weaker form of `Conflicts` that applies primarily for apt to select install/update candidates.
This should hopefully not be needed in most circumstances, but in the cases that it is needed, it is available.
The code is also slightly tweaked to have the appropriate warnings for all Debian-specific tags not wrapped in a conditional now.

Add Debian-specific "Breaks" support

---

Makefile

This change broke installing debbuild for Debian 7 and Ubuntu 12.04.
This reverts commit 84ba90d7b0891a69d230b82da67be5a70b6e292e.

Revert "Use 'install' in Makefile."

---

debbuild

This fixes building packages for Debian's arm64 (aarch64) and armhf (armv7hl) architectures.

Add arm64 and armhf %optflags definitions

---

debbuild

`dpkg` allows for package names to have `.` in it (such as `libglib2.0-0`). However, the regular expression set for this would fail on these packages and ignore them. Thus, this regular expression needs to be updated to match on this.

Ensure identified library deps match to packages with '.' in names

---

debbuild
macros/macros.in

In the event that a stage script (that is, the scripts for `%prep`, `%build`, `%install`, `%check`, or `%clean`) ends with a command that exits with a non-zero error code, the script should fail and the build should fail. Prior to this change, debbuild did not do this, which allowed for package builds to complete successfully despite failures that occurred throughout each stage of the package build.
This change now mimics how `rpmbuild(8)` calls stage scripts so that package build failures occur in a similar manner.

Correctly abort stage scripts and the build when errors occur

---

macros/macros.in

On virtually all Linux distributions (including Debian and RPM based ones), `%_localstatedir` is set to `/var` and `%_sharedstatedir` is set to `/var/lib`.
In RPM, these are set in `platform.in` based on what is passed into the `configure` script at build time, but debbuild doesn't work that way.
So, we set it correctly in the macros file so that everyone will Do the Right Thing(TM).

macros: Set %_localstatedir and %_sharedstatedir correctly

---

debbuild

This allows debbuild to be used on non-Debian-based systems to build Debian packages with the caveat that all dependencies must be fully specified (since the dependency generator will obviously not work).
This is useful for supporting foreign environments for package builds, as well as doing cross-target package builds, given the right environment settings.

Add --nodeps support to debbuild

---

debbuild
debbuild.spec

The %files section in spec files can contain a filename to read additional
filelist from. This file may be generated while the building process.
Without this patch the file is ignored because only the contents of the
%files section are processed.
This patch
* adds all the steps to process a file which can be generated at buildtime.
* It prevents "expandmacros" from substituing %dir with %{dir}.
* Adds a Requires for liblocale-gettext-perl to the spec file

added support for '%file -f <filname>' in spec

---

.circleci/config.yml
cpanfile
t/001_version.t

Add CI to run tests.
Right now, there is only one very basic test, which verifies that `debbuild --version` works.
Substantially more work will need to be done before debbuild can get through the prep phase within the container. (We'll need to move much of the `%install` macro in debbuild.spec into a `make install` so that we can run it in the container.)

Add CI and very basic tests

---

.circleci/config.yml
.gitignore
Makefile.in
configure
debbuild
debbuild.spec
t/001_version.t

Factor parts of the specfile out into a separate Makefile.in. There is deliberately no Makefile.ac because we're not actually using autotools.
Provide a "configure" script that implements a minimal compatabile
subset of autotools configure functionality, namely, the part where
it composes paths and then substitutes values into a Makefile.in to
create a Makefile.
The Makefile currently provides targets for substituting the version into the debbuild script, running tests, and installing.
This should not change any runtime functionality, but it does alter the development workflow.
Motivation: breaking out build and install steps into a Makefile makes it easier to reuse them in tests and during development. Tests in particular will [need to change some file …

Introduce Makefile and configure script

---

Makefile.in
debbuild.spec

Macros provided by packages should be installed into the vendor
directories instead of the local configuration directory.

Install macros into /usr/lib/debbuild/macros.d instead of /etc/debbuild

---

debbuild
macros/macros.in

This PR includes a couple of macro updates synchronized from the RPM 4.15 release, and a bug fix for `%getconfdir` to point to the correct path consistently.

Misc improvements to macros

---

Makefile.in
configure
debbuild
debbuild.spec
t/001_version.t

Add new mechanism for providing build-time configuration to debbuild.
The old mechanism of sed-ing into the source code was brittle and hard
to get right.
Instead, use the __DATA__ section at the end of the debbuild file to
append an rpmrc-format file with build-time configuration. debbuild
parses this at startup and uses it if it exists. If not, it falls back
to default values to ensure that debbuild will still run directly in its
source form.
The configuration added at build-time is:
- version
- debconfigdir
- sysconfdir
which will allow unit tests to load macros and config from non-installed locations.
debrc parsing has been centralized to a helper function used for this purpose.

Add ability to configure at build-time without sed 

---

macros/platform.in

Debian/Ubuntu systems default to architecture-specific library directories,
and the `%_initddir` and `%_rundir` macros were erroneously not defined in
the platform macros at all.

macros/platform: Add missing basic defaults and strip irrelevant comment

---

macros/macros.in

These macros exist for usage with %ifarch, ExclusiveArch, and ExcludeArch
and to provide some compatibility with RPM specs using them.

macros: Add analogues of some RPM architecture alias macros

---

Makefile.in
debbuild
debbuild.spec

The spec file for debbuild was quite old, and lacked some good
practices followed by downstream packaging in Fedora and other locations.
Moreover, debbuild is no longer developed by Kris Deugau, so referencing
DeepNet in the title is not particularly useful or helpful anymore.
And finally, update copyright statements to reflect current reality.

Modernize packaging for debbuild and update man page and copyright

---

debbuild

Fix a regression where only the last optflags entry in the debrc was
preserved.
When debbuild switched to using read_debrc_from_handle, a bug was
introduced where a subsequent entry with a duplicate name overwrote
previous ones, since the return value of that sub was stored as a simple
hash. (I didn't realize at the time that the rpmrc format allowed
multiple entries with the same name.)
Enhance read_debrc_from_handle to return a hash of arrayrefs, containing
each of the entires for a particular name.
This should fix #127 .

Handle multiple debrc entries per name

---

debbuild

This change broke some macros that embedded escaped characters.
This reverts commit c2aa351938af86a0c52649185cf44d9cb6e997d9.

Revert "Enable backslash escape in shell scripts."

---

macros/macros.in

BSD's sed requires an `extension` for the `-i` option, even an 'empty' (`""`) extension to suppress creation of a backup for 'in-place' editing. With `'%{__sed_i}` it should be easier to write portable specfiles for both GNU/Linux and BSD based systems. The latter should simply redefine
```
%__sed_i /bin/sed -i ""
```
in a local macro file or
```
%global __sed_i /bin/sed -i ""
```
in a specfile.

Support sed 'in-place' replacement on BSD.

---

debbuild

Reduce escaped backslash only for use as escape backslash, e.g. `\\n` becomes `\n`, but `\\\\\[` stays intact.

Fix issue #131.

---

debbuild

Quck-and-dirty test on MacOS and [cwebbin](https://github.com/ascherer/cwebbin.git) with the obvious non-`auto` changes in `cwebbin.spec`
```
%setup -c -a1 -a2
%patch2 -p1
%patch -P4 -p1
```
and the local invocation `./debbuild -vv -bp SPECS/cwebbin.spec` works as expected.
Positive result confirmed on the main Linux system.

Fix issue #135.

---

debbuild

With 51dccbd392f7d82ea1d30f53d86e811ccfb11994, debbuild switched
from using regular expressions to do fuzzy matching on stanzas
declared in a subpackage to using exact literal matches.
However, the extra escaping of parens that was supposed to be removed
as part of changing to using exact literal matching was left in,
causing the keys read in for `Requires(pre)` and `Requires(preun)`
to be escaped and thus fail to match with the right value in the
quote word group.
This extra escaping was necessary with the fuzzy matching logic
because otherwise the parens would be considered as a capturing
group in a regular expression. Since we do not use regular
expressions to identify the stanzas anymore, this became
unnecessary.
Dropping the statement that does the extra escaping fixes the
handling …

Remove unnecessary escaping for Requires(pre)/Requires(preun)

---

debbuild

Currently, we completely skip over Supplements clauses in subpackages.
This means that weak dependencies declared in this way will not be in
the resulting package. Because Debian doesn't have this type of
relationship, map it to the weaker relationship Enhances and print a
warning for the user.
Fixes #143

Process Supplements in subpackages

---

debbuild

Currently, we completely skip over post-install dependencies. This means
that they won't be included in the resulting package at all, which could
break post-install scriptlets. Debian packages don't have a concept of
post-depends, so upgrade them to regular dependencies.
Fixes #141

Process Requires(post) and Requires(postun)

---

debbuild

I'm in the process of upgrading `po/debbuild.pot` and found two _almost_ identical strings. Colon added to make all these warnings similar.

Assimilate warning texts.

---

debbuild
po/de/debbuild.po
po/debbuild.pot

@Conan-Kudo thanks for the translation badge.  I've noticed the warnings about the spacing discrepancies, hence this PR.
See [Wikipedia](https://en.wikipedia.org/wiki/History_of_sentence_spacing) for details of differences between English and French; German also uses single spaces between sentences.

Straighten English vs. French spacing.

---

debbuild

Fix missed spacing change in 'debbuild'.

---

Makefile.in
debbuild.spec

Cool, this is the output of `LANGUAGE=uk debbuild -ba -v -S git_am SPECS/debbuild.spec`:
```
Це debbuild, версія 20.01.0
Виконуємо (%prep): /bin/sh -e /var/tmp/deb-tmp.prep.37764
Виконуємо (%build): /bin/sh -e /var/tmp/deb-tmp.build.29943
checking for pod2man... pod2man
checking for msgfmt... msgfmt
checking for /etc/os-release... yes
Reading Makefile.in...
Substituting the following values:
msgfmt=msgfmt
localedir=/usr/share/locale
pod2man=pod2man
datadir=/usr/share
bindir=/usr/bin
exec-prefix=/usr
version=20.01.0
libdir=/usr/lib/x86_64-linux-gnu
sysconfdir=/etc
datarootdir=/usr/share
libexecdir=/usr/libexec
debconfigdir=/usr/lib/debbuild
exec_prefix=/usr
mandir=/usr/share/man
prefix=/usr
Writing Makefile...
Done.
cp debbuild debbuild.out
echo "\
version:20.01.0\n\ …
```

Install Ukrainian translation module.

---

debbuild
t/003_baseosver.t
testdir/baseosver/debian10/os-release
testdir/baseosver/debian_sid/os-release

- Do not overwrite OS-specific macros from lsb_detection if they are
defined in .debmacros
- Correctly multiply Debian version to create %debian_version
Fixes #157

OS-specific macros in lsb_detection

---

Makefile.in
configure

Maybe this can come from `configure`? – Yep!

Dynamic detection of ISO-639-1 locale codes.

---

debbuild
po/de/debbuild.po
po/debbuild.pot
po/it/debbuild.po
po/tr/debbuild.po
po/uk/debbuild.po

Apart from the variations of `warning`, this seems to be the only major duplicate in `po/debbuild.pot`.

Merge matching substring

---

debbuild
debbuild.spec
macros/macros.in

Currently, it's not possible to use a gem as a source file like in
other tools such as rpmbuild. This means that the source can't be
obtained from rubygems.org, which is often desirable, and separate
deb-specific logic is required when packaging gems for both deb and
rpm-based systems. This adds support for using .gem files directly.

Add support for gems as source files

---

debbuild

Currently, this fails on distributions that ship older versions of Ruby,
such as Ubuntu 16.04, because the silent flag was introduced later.
Because we still need to support those distros, remove the usage here.

Remove --silent flag from gem unpack call

---

debbuild

For handling architecture and operating system conditionals, we
translate them into the generic form first before processing.
However, we have been incorrectly formatting these translated
conditionals, so the rest of the evaluation fails.
This change fixes it so that it is translated to the proper generic
form as expected by the conditional handling code.

Fix arch/OS conditional statement translation to generate well-formed ones

---

debbuild

In circumstances where a subpackage name had `-n` in it, debbuild
would incorrectly match on that and fail to put the expected prefix
for binary package names declared using the subpackage shorthand
form of `%package bar` such that `%package bar-nox` for source package
`foo` would make a package `bar-nox` instead of `foo-bar-nox`.
Fix this by ensuring that we match on `-n` used as an option by
checking also for a whitespace character immediately before and after,
as that is obviously not a package name if whitespace characters exist.

Fix detection of subpackage naming format

---

debbuild

replacemacros() is looping all available macros in input, to convert
them to %{} syntax. The conversion used to use s///g, which causes all
instances to be replaced in one pass. This causes wrong replaces in some
cases. Consider following input:
%cmake
%cmake_build
When one replaces %cmake with %{cmake} with g flag, latter line would be
%{cmake}_build, causing wrong expansion to happen at later point.
This should fix #181

expandmacros: replace gobal macros one at time

---

debbuild

This builds on top of pull request #187.
When using --eval to expand a macro, there likely will not be
anything after a macro. This allows macro check to match even
if input ends directly after macro.
The regex was suggested by @ascherer.
Fixes #181.

expandmacros: replace global macro even as last thing of input

---

debbuild

The arch/os conditionals are special in that they take space separated
arguments and tokenize them to transform them into standard conditionals.
However, it's very common for architecture lists to be constructed
with macros. For example: `%ifarch %{64bit_arches}` may be valid
input with the assumption that `%64bit_arches` is defined earlier
in the spec file. And that macro may also include others that need
to be expanded. Previously, this hasn't worked and debbuild would
decompose this into `%if "%{_arch}" == "%{64bit_arches"`, which
would get evaluated later into a stanza that wouldn't match to anything.
With this change, debbuild now expands all macros *first* before
decomposing the conditional into standard conditionals for further
processing.

Expand macros before processing %if(arch|os)/%ifn(arch|os) stanzas

---

cpanfile
debbuild

- `expandmacros` was rewritten to replicate the behavior of `rpm` with serial reading of the macros.
In some cases `spec` can be processed the wrong way when the macro redefinition is performed within `spec`.
Originally `debbuild` processing all the macros by type for all occurences at once. This approach can lead to the mistakes when the macro should be redefined between these occurences.
- Files processing for the packages and subpackages was redesigned also
- Implemented `%exclude` support for the files
- Minor fixes for patch apply
- Some addition for internall debugging. `%_debbuild_debug_level` macros can be set in project config for some debugging purposes. 
- Use `%_buildshell` macro from project config to use for internal shell script processing. `dash` works different way than …

Implement Lua macro support and redesigned expandmacros

---

debbuild

I have a project that uses %include and it fails to build with:
readline() on closed filehandle $fh at /usr/bin/debbuild line 607.
In fact, the test case in testdir/dummy.spec will also demonstrate this behavior.
This is due to commit 3d0dba6e (Handle multiline macros in specfiles) turning $fh into a global.  When parse_spec opens the included file, it reuses the global file handle variable and when it completes, it closes it, leading to failure.
This commit fixes the issue by restoring the behavior of parse_spec owning its file handle and then passing it as an argument to consumers. Due perl's open operation only creating new file handles when the variable to be used is undefined, it's insufficient to keep a copy of the variable when parse_spec recurses.

Fix %include handling by passing file handle

---

.circleci/config.yml

CentOS Linux 7 is EOL, so move forward to AlmaLinux 9.

CI: Upgrade to AlmaLinux 9

---

debbuild

If a directory is given the `%dir` directive we're signalling that we only want to manage the directory itself, not the contents.
We shouldn't be recursively updating the ownership, instead we should only update the ownership on the directory itself.

Don't recursively chown directories if we're not managing their content

---

debbuild

Closes https://github.com/debbuild/debbuild/issues/254.
`debbuild` has some problems on Ubuntu 24.04 and Debian 12 with parsing package requirements. 
On Ubuntu 24.04, the problems were caused because of usage of `readlink` which was returning `usr/lib` (without quotes) when queried with argument `"/lib"`, while the expected return was `/usr/lib`. Changed `readlink` to `abs_path` from `Cwd` to prevent any possible future issues with that.
On Debian 12, additionally were problems with `libc.so.6`, to be more exact -- `dpkg-query -S libc.so.6` is returning `/lib/x86_64-linux-gnu/libc.so.6`, while for all of the other libraries the prefix is `/usr/lib`. According to [dpkg specifications](https://man7.org/linux/man-pages/man1/dpkg-query.1.html), when the query starts with `/`, `dpkg-query -S` …

Fix the usrmerge handling to work properly on Ubuntu 24 and Debian 12

---

debbuild
debbuild.spec

Distros are meant to set the vendor, not the tool. So if debbuild gets included in a distribution it may have a different vendor than 'debbuild'. Rpm doesn't have rpm as vendor either after all. Debian for example defines _vendor as "debian" for rpmbuild. The internal _debbuild macro is set to the version of debbuild so seems like a good way to identify the tool

Use %_debbuild instead of vendor for debbuild conditionals

---

debbuild

This PR improves on PR https://github.com/debbuild/debbuild/pull/255 on (K)Ubuntu and possibly Debian systems.
For whatever reason, `dpkg-query` does not seem to have an option to follow symlinked paths on its own. System stuff like `libc.so.6` is located under path `/usr/lib`, which is symlinked to path `/lib`.
By replacing the absolute path of such library files, we can skip the double invocation of `dpkg_query_paths` and the quite involved resolution to the same result (including a call to `abs_path` at that).
This PR was developed on **Kubuntu 24.04.1 LTS** with **debbuild 24.12.0** with example package [mmix.spec](https://github.com/ascherer/mmix/blob/local/mmix.spec).

PR #255: Why not look in absolute path?

---

po/debbuild.pot

Yesterday I forgot to fix this typo in my `aspell` comitt. :smile:

Fix typo in translatable string.

---

po/debbuild.pot

By leaving out the `-j` option of the `xgettext` incantation and by relying on `git diff` to restore vital header information, we can easily create an up-to-date version of the **debbuild.pot** file that truely matches the **debbuild** program. This eliminates not only shifted/outdated line information for the translatable strings but also several strings that are no longer in use.

Issue #265: Purge old line numbers in DEBBUILD.POT.
